
 
 
 




rem Clean up the results directory
rmdir /S /Q results
mkdir results

rem Synthesize the VHDL Wrapper Files


echo 'Synthesizing example design with XST';
xst -ifn xst.scr
copy xilinx_ram_65536_exdes.ngc .\results\


rem Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
copy ..\..\xilinx_ram_65536.ngc results\


rem  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
copy ..\example_design\xilinx_ram_65536_exdes.ucf results\

cd results

echo 'Running ngdbuild'
ngdbuild -p xc6slx75t-fgg676-2 xilinx_ram_65536_exdes

echo 'Running map'
map xilinx_ram_65536_exdes -o mapped.ncd  -pr i

echo 'Running par'
par mapped.ncd routed.ncd

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level Verilog model'
netgen -ofmt verilog -sim -tm xilinx_ram_65536_exdes -pcf mapped.pcf -w -sdf_anno false routed.ncd routed.v
